version: "3.9"
networks:
    services-network:    
        driver: bridge
services:
    postgres-db:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: T1TestTaskDB
        ports:
           - 5432:5432
        networks:
            - services-network
        volumes:
            - postgres-data:/var/lib/postgressql/data
    t1-test-task-api:
        container_name: t1-test-task-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        networks:
            - services-network
        depends_on:
           - postgres-db
volumes:
    postgres-data: